# value we define overwrite the default values in service and deployment
appName: cartservice
appImage: gcr.io/google-samples/microservices-demo/cartservice
appVersion: v0.10.1
appReplicas: 2
containerPort: 7070
containerEnvVars:
- name: PORT
  value: "7070"
- name: REDIS_ADDR
  value: redis-cart:6379

servicePort: 7070
# ClusterIP is the default value we can take it out
# serviceType: ClusterIP
