# value we define overwrite the default values in service and deployment
appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.10.1
appReplicas: 2
containerPort: 7000
containerEnvVars:
- name: PORT
  value: "7000"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 7000
# ClusterIP is the default value we can take it out
# serviceType: ClusterIP
