# value we define overwrite the default values in service and deployment
appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.10.1
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"

servicePort: 5000
# ClusterIP is the default value we can take it out
# serviceType: ClusterIP
