# value we define overwrite the default values in service and deployment
appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.10.1
appReplicas: 2
containerPort: 3550
containerEnvVars:
- name: PORT
  value: "3550"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 3550
# ClusterIP is the default value we can take it out
# serviceType: ClusterIP
