# value we define overwrite the default values in service and deployment
appName: shippingservice
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.10.1
appReplicas: 2
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"

servicePort: 50051
# ClusterIP is the default value we can take it out
# serviceType: ClusterIP
